spring:
  application:
    name: DevelopmentBooks

bookstore:
  mongo:
    username: admin
    password:
    host: cluster1.ywkinwj.mongodb.net
    database: bookstore
    options: ?retryWrites=true&w=majority&appName=Cluster1

server:
  servlet:
    context-path: /bookstore
  port: 8080