spring:
  application:
    name: DevelopmentBooks

bookstore:
  mongo:
    username: admin
    password:
    host: cluster1.ywkinwj.mongodb.net
    database: bookstore
    options: ?retryWrites=true&w=majority&appName=Cluster1

server:
  servlet:
    context-path: /bookstore
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,env,beans,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO